### ISSUE TITLE
Cannot import 'requests.packages.urllib3'

### ISSUE THREAD

**Issue by jmschrei** [uwescience/myria-web#249]
This is a very odd bug for me, so I figured I'd post it here.

When I run  "python google_appengine/dev_appserver.py /home/jmschr/Desktop/myria-web/appengine", I get "ImportError("No module named 'requests.packages.urllib3'). The error comes from myria-web/appengine/requests/packages/\_\_init\_\_.py. If I go a Python terminal, I can import requests, requests.packages.urllib3, and urllib3 independently. However when I run this program through the appengine python program it seems to forget I have them.

I renamed the requests file seeing as I had requests already installed, and that didn't seem to help (it now couldn't find requests). I also try directly importing urllib3 into the namespace in packages/__init__.py, but it doesn't know what urllib3 is (even though it works for me in a python terminal). 

Any suggestions?

**Comment by dhalperi** [comment]
Can you try the app engine launcher and see if the bug still occurs?


----
Daniel Halperin
Director of Research for Scalable Data Analytics
eScience Institute
University of Washington

**Comment by jmschrei** [comment]
I can't find the app engine launcher, can you point me in the right direction?

**Comment by billhowe** [comment]
https://www.google.com/search?q=app+engine+launcher

On Wed, Feb 11, 2015 at 4:52 PM, Jacob Schreiber <notifications@github.com>
wrote:

> I can't find the app engine launcher, can you point me in the right
> direction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria-web/issues/249#issuecomment-73997507>
> .
>



-- 
Bill Howe
Associate Director and Senior Data Science Fellow, UW eScience Institute
Affiliate Faculty, Computer Science & Engineering
University of Washington
To acknowledge eScience: "Supported in part by the University of Washington
eScience Institute"

**Comment by jmschrei** [comment]
Thanks Bill. I have that, and was using the dev_appserver.py script in it. Is there another script I should be using?

**Comment by dhalperi** [comment]
I guess the instructions aren't that helpful. Here's my experience on Mac:

1. from this link: https://cloud.google.com/appengine/downloads, I see this:
    ![screen shot 2015-02-11 at 5 28 29 pm](https://cloud.githubusercontent.com/assets/526415/6160132/6f172e72-b213-11e4-9e16-2841c6e27b32.png)

2. As part of downloading and installing that, it sets up an application shortcut
    ![screen shot 2015-02-11 at 5 29 17 pm](https://cloud.githubusercontent.com/assets/526415/6160143/881653a8-b213-11e4-9876-b6a01edf91f5.png)

So the instructions are "obvious" to us... I'm guessing that maybe you're using a different platform?

**Comment by jmschrei** [comment]
I'm on Ubuntu and the app does not come natively with Google AppEngine.

I followed this thread to try to get it: http://askubuntu.com/questions/308534/google-app-engine-gui-launcher-for-ubuntu-13-04

I downloaded wxglade and wxversion as suggested, then checked out the repo using subversion as they suggested, giving me the google-appengine-launcher folder with GoogleAppEngineLauncher.py in it.

However, whenever I try to run GoogleAppEngineLauncher.py I get "wxPython is not available", even after using `sudo apt-get install python-wxversion python-wxglade` as was suggested.

**Comment by dhalperi** [comment]
Hmm. This isn't really something we can help debug, as none of us develop on Linux.

`<overly honest>`
I'm inclined to say "those who make themselves use awful tools [Linux] deserve to suffer the consequences"...  but that's probably not helpful.
`</overly honest>`

If one of us finds time, maybe someone in the @uwescience/myria team can find a way to get Desktop Linux up and running and debug the process of launching the development server. Unfortunately, I'm not sure it's going to be a top priority.

**Comment by dhalperi** [comment]
(I did send an email asking the group to check out this issue.)

**Comment by jmschrei** [comment]
I find your overly honest statement a bit ironic given that you don't have documentation for how to install and use Myria on a desktop system with a freely available iso.

**Comment by dhalperi** [comment]
I'm not going to dignify the laughable implication that that you didn't "opt-in" to Ubuntu... no need to feed the trolls.

I don't have access to Ubuntu desktop, but I did just go through the [extraordinarily simple and fully documented myria-web](https://github.com/uwescience/myria-web#initial-setup) setup steps (I skipped step 2, as it's not mandatory) on our Ubuntu server, and everything worked fine:

```sh
mkdir /disk1/sandbox
cd /disk1/sandbox
git clone https://github.com/uwescience/myria-web
wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip
unzip google_appengine_1.9.17.zip
cd myria-web
git submodule init
git submodule update
../google_appengine/dev_appserver.py --port=12345 appengine
```

and in a new window

```sh
curl -i localhost:12345
```

and it worked:

```
HTTP/1.1 301 Moved Permanently
location: http://localhost:12345/editor
cache-control: no-cache
content-type: text/html; charset=utf-8
Content-Length: 0
Server: Development/2.0
Date: Fri, 13 Feb 2015 02:13:19 GMT
```

Of course, you may not need to set the appengine port if your machine is not using the default port; our server is.

Seems like you have a personal problem.

**Comment by dhalperi** [comment]
Note that you should not need to install any packages in the Python system -- App Engine does not use them. The packages it uses are all included in the app engine kit or in the `myria-web` submodules.

**Comment by jmschrei** [comment]
That summary was excellent, it seems to have fixed whatever issue I was having. I would suggest putting that in the myria-web README you linked to. However, while it is working, I get repeatedly

```
INFO    2015-02-13 21:14:58,366 module.py:718] default: "POST {command} HTTP/1.1" 400 61 
Unable to create 'parsetab.py'
[Errno 30] Read-only file system: 'parsetab.py'
```

where command in {/optimize, /dot, /compile, /plan}, ending with 

```
WARNING    2015-02-13 21:15:00,535 myrialang.py:1238] Error converting Store(public:adhoc:JustX)[Apply(x=$0)[Scan(public:adhoc:TwitterK)]]: convert <class 'raco.alphebra.Store'> to sql
INFO    2015-02-13 21:15:00,541 module.py:718] default "POST /compile HTTP/1.1" 200 978
```

These don't seem to prevent me from loading the frontend in a browser though. The browser has a warning saying that Myria will be reserved for research experiments soon; can I go ahead and ignore that since I'm running on a local machine?

**Comment by dhalperi** [comment]
That is the aforementioned step 2 on the install docs. It is not a correctness error, only a performance hit



—

**Comment by jingjingwang** [comment]
"can I go ahead and ignore that since I'm running on a local machine?" -- yes you're exactly right.

"[Errno 30] Read-only file system: 'parsetab.py'" -- hmm, read-only file system?

**Comment by dhalperi** [comment]
Read only because of the app engine sandbox



—

**Comment by jmschrei** [comment]
I'm going to go ahead and close this issue then, since it's been resolved. Thank you!

**Comment by dhalperi** [comment]
Can you explain what step in there was not directly implied by the instructions in the install step? The clone and fixing submodules were explicit, the "run dev_appserver with path to appengine" just requires getting the path correct.

What were you doing differently?

**Comment by jmschrei** [comment]
I likely downloaded the incorrect google appengine and/or did not handle working with it correctly. Having a specific wget/unzip command was super useful to me, as I am not familiar with using it at all prior to this.
