### ISSUE TITLE
non-deterministic bug loading profiler (think it's a race condition)

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-web#250]
@domoritz thoughts appreciated.

I occasionally see this log in the Javascript console: `Uncaught TypeError: Cannot read property 'numTuples' of undefined      graph.js:775`

[Tracking this code down](https://github.com/uwescience/myria-web/blob/8f59ab8a7401f1146daada0a00d4b2a4f88ae497/appengine/js/graph.js#L775), it seems that the `linkOrigins` dict is populated (comes from the query plan), but the `linkAttr` dict is not.

`linkAttr` is populated during [`loadCosts`](https://github.com/uwescience/myria-web/blob/8f59ab8a7401f1146daada0a00d4b2a4f88ae497/appengine/js/graph.js#L178), which is called very early -- [upon `Graph` creation](https://github.com/uwescience/myria-web/blob/8f59ab8a7401f1146daada0a00d4b2a4f88ae497/appengine/js/graph.js#L7). 

The main thing I see is that `loadCosts` populates `linkAttr` [using `d3.csv`](https://github.com/uwescience/myria-web/blob/8f59ab8a7401f1146daada0a00d4b2a4f88ae497/appengine/js/graph.js#L187), which is an asynchronous call. So it seems that if this call takes a little while, `linkAttr` may not be ready when we get to the code that fails.

One solution is to switch to jQuery for loading this data and force synchronous loading (and conversion from CSV). This change would make `loadCosts` a blocking function and add a critical section to the entire page.

Opinion and alternate suggestions?

**Comment by dhalperi** [comment]
dependency management is hard :P.

**Comment by domoritz** [comment]
Oh yeah, callback hell and asynchronous IO bites again. I thought this was resolved by https://github.com/uwescience/myria-web/blob/master/appengine/js/graph.js#L7 Draw should not be called until the call finishes. The callback is only called after the request is completed. This is odd.

**Comment by dhalperi** [comment]
You are obviously right, and I've realized the bug is completely something else. Thanks for the explanation though!!

**Comment by dhalperi** [comment]
In other news, my claim that this is non-deterministic was also false. I am just wrong today...
