### ISSUE TITLE
query #63082 accepted but not running?

### ISSUE THREAD

**Issue by sophieclayton** [uwescience/myria-web#258]
is there a reason why a query that has been accepted hasn't started running?
also, seems like 5 machines are down.

**Comment by domoritz** [comment]
A network card was overheating. It should work now.

**Comment by billhowe** [comment]
....another vote for AWS!

On Tue, Feb 24, 2015 at 5:04 PM, Dominik Moritz <notifications@github.com>
wrote:

> A network card was overheating. It should work now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwescience/myria-web/issues/258#issuecomment-75885503>
> .
>



-- 
Bill Howe
Associate Director and Senior Data Science Fellow, UW eScience Institute
Affiliate Faculty, Computer Science & Engineering
University of Washington
To acknowledge eScience: "Supported in part by the University of Washington
eScience Institute"
