### ISSUE TITLE
No Physical plan for while loop query

### ISSUE THREAD

**Issue by bmyerz** [uwescience/myria-web#274]
On sigma clipping or powers of 2, the physical plan text is shown briefly (#optimized), but js crashes while rendering the d3.

![image](https://cloud.githubusercontent.com/assets/1979690/6948391/65b55438-d862-11e4-9132-add79605152b.png)

![image](https://cloud.githubusercontent.com/assets/1979690/6948413/8e1d88a0-d862-11e4-95d8-da59deed2255.png)

**Comment by dhalperi** [comment]
Known issue – iterative physical plans are not visualizable. In-progress work at https://github.com/uwescience/myria-web/pull/152

**Comment by dhalperi** [comment]
Fyi @stechu
