### ISSUE TITLE
JSON dataset link on Results tab of query editor should open new tab/window

### ISSUE THREAD

**Issue by senderista** [uwescience/myria-web#293]
When I'm running multiple queries, I find it distracting to have to remember to hit the Back button to return to the query editor after viewing JSON results. I find the behavior of the JSON query plan link to be much more natural: open a new tab/window to display results. This is a matter of taste, of course, but I don't feel it's appropriate to interrupt the query editor workflow with in-browser display of results.

**Comment by BrandonHaynes** [comment]
This has bugged me forever as well.  Fixed in associated PR.

**Comment by senderista** [comment]
Awesome, thanks Brandon!
