### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by bmyerz** [uwescience/myria-web#306]
Something changed (in travis?) and now master (2a1dfc1...) doesn't pass the tests.

https://github.com/uwescience/myria-web/pull/305

**Comment by domoritz** [comment]
Looks like it's coming from raco. https://travis-ci.org/uwescience/myria-web

**Comment by BrandonHaynes** [comment]
Probably the httmock issue.

**Comment by senderista** [comment]
No, it's because the mocked dataset JSON blobs in `myria-web/appengine/test/test_myria_up.py` don't have the new `howPartitioned` attribute.

**Comment by bmyerz** [comment]
@senderista nice, thanks!!
