### ISSUE TITLE
I'm not presently able to execute any of the data load data from the demo UI

### ISSUE THREAD

**Issue by metasoarous** [uwescience/myria-web#316]
I'm here trying to run one of the data load commands, but am unable to get it to work.

http://demo.myria.cs.washington.edu/editor

I get this:

```
Error 400 (Bad Request): Error 200 (OK): {"url":"http://52.91.5.101:8753/query/query-1760","queryId":1760,"rawQuery":"T1 = load(\"s3://uwdb/sampleData/TwitterK.csv\",\n        csv(schema(a:int,b:int)));\nstore(T1, TwitterK);","logicalRa":"Parallel","plan":{"type":"SubQuery","fragments":[]},"submitTime":"2017-04-07T22:25:28.891Z","startTime":"2017-04-07T22:25:28.914Z","finishTime":"2017-04-07T22:25:28.915Z","message":null,"elapsedNanos":127458,"status":"SUCCESS","profilingMode":[],"ftMode":"NONE","language":"datalog"}
```

**Comment by senderista** [comment]
Hi, it looks like you had selected the query language as "Datalog", but the query is in MyriaL. I tried this and got the same error you pasted here, but it works fine when the selected query language is "MyriaL". Certainly the error is completely misleading and uninformative, though--we'll work on fixing that.

**Comment by metasoarous** [comment]
Oh dear; Thanks for catching for me!

**Comment by senderista** [comment]
Opened https://github.com/uwescience/myria-web/issues/317 for this.
